### ISSUE TITLE
[스프린트 #6] Model Directory 정리 : data, model, and config

### ISSUE THREAD

**Issue by hojunee** [strong-win/stock-craft#38]
# 기능 Issue

## Contents
본 issue는 ML서버 내부의 Folder Spec을 정의하는 것을 목표로 합니다.

## 핵심 작업사항
1. local 환경에 저장할 파일들 - `model_discriminator.pt`, `model_generator.pt`, `data.csv` - 의 file name spec을 정의합니다.
2. MongoDB의 Document schema에 이를 반영합니다.

## 진행사항 체크리스트
1. Folder/File name spec 정의
- [x] @hojunee  
- [x] @handal95 
2. MongoDB의. Document schema에 이를 반영
- [x] @hojunee 
---

## Expected Folder Spec
- `MSID` :  모델셋(data, modelD, modelG를 갖는 struct)의 고유 id
```text
model/
  ...
  data/
    data_ MSID.csv
    ...
  model/
    model_gen_ MSID.pt
    model_dis_ MSID.pt
    ...
```

**Comment by hojunee** [comment]
Model을 관리할 때 model에 관한 정보를 대부분 local(`.pt`, `.csv`)에 저장하는 방향으로 구상하고 있습니다.
새로운 Document 를 넣기 위해서는 mongoDB에 이러한 파일들의 경로를 string으로 넣고자 하는데요,
**이 경로를 구체적으로 정해주시면** 제가 모델셋 데이터를 생성하는데 아주 큰 도움이 될 것 같습니다. :>

확인 후 예상되는 directory spec 말씀해주시면 감사하겠습니다.
FYI : @handal95

**Comment by handal95** [comment]
금요일 오후 6시 31분 회의실로 오셔서 논의 마무리해봅시다

**Comment by handal95** [comment]
> # 핵심 작업사항
> local 환경에 저장할 파일들 - model_discriminator.pt, model_generator.pt, data.csv - 의 file name spec을 정의합니다.

- Local 환경에 저장할 파일들을 TimebandCore를 pickle을 이용해서 python binary 형태의 파일 하나만을 저장합니다.

- 파일은 `models/` 디렉토리 내에 `XXXX.pkl` 형태로 모델 코어파일을 관리합니다.

- 기존 TIMEBAND 파일들은 원 데이터와의 동기화 부분을 고려해서 새로운 repository에 fork해와서 관리합니다. (기존 TIMEBAND코드들은 현 repo에서 내릴 예정)

- DB Schema의 명칭에 대해서는 11월 27일(일) 추가 논의합니다.

**Comment by hojunee** [comment]
- MongoDB에 `stock` 이라는 Collection을 추가하고, App Server와 연동하는 부분을 추가했습니다.
- 상일님이 마무리해주시는대로 이를 연동해서 마무리합니다. issue를 close합니다.
